title = "TOML Example"

[owner]
name = "Ankush Bhardwaj"
dob = 1979-05-27T07:32:00-08:00

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[clients]
data = [ ["gamma", "delta"], [1, 2]]